plugins:
  - rubocop-rspec
  - rubocop-yard

AllCops:
  NewCops: enable

# Keep indentation consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Keep indentation consistent
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

# It's ok to have longer lines
Layout/LineLength:
  Max: 160

# Not all plugins use all keyword arguments, it's normal.
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# It's ok to have longer methods, while keeping readability.
Metrics/AbcSize:
  Max: 110

# It's ok to have longer methods, while keeping readability.
Metrics/BlockLength:
  Max: 50

# It's ok to have longer methods, while keeping readability.
Metrics/BlockNesting:
  Max: 5

# It's ok to have longer classes, while keeping readability.
Metrics/ClassLength:
  Max: 250

# It's ok to have longer methods, while keeping readability.
Metrics/CyclomaticComplexity:
  Max: 40

# It's ok to have longer methods, while keeping readability.
Metrics/MethodLength:
  Max: 100

# kwargs should not count towards max parameters list.
Metrics/ParameterLists:
  CountKeywordArgs: false

# It's ok to have longer methods, while keeping readability.
Metrics/PerceivedComplexity:
  Max: 40

# These tests are not describing any class or module
RSpec/DescribeClass:
  Exclude:
    - 'spec/scenarios/code_quality_spec.rb'
    - 'spec/scenarios/documentation_spec.rb'
    - 'spec/scenarios/packaging_spec.rb'

# It's ok to have scenarios having multiple lines
RSpec/ExampleLength:
  Max: 140

# It's ok to have test scenarios having several expectations
RSpec/MultipleExpectations:
  Max: 70

# It's ok to have nested groups in RSpec.
RSpec/NestedGroups:
  Max: 5

RSpec/RemoveConst:
  Exclude:
  # We can't use stub_const or hide_const, because we need to remove it so that the test itself redefines it.
  # Using RSpec's mocking framework would prevent the new one to be used.
  - spec/spec_helper.rb

# I don't want to pollute my code with something that should be integrated in the language
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# I don't want to pollute my code with something that should be integrated in the language
Style/MutableConstant:
  Enabled: false
